In [1]:
# Import Library
import pickle
import json
import pandas as pd
import numpy as np

In [2]:
# Load Model

with open('scaler_final.pkl', 'rb') as file_1:
  scaler_inf = pickle.load(file_1)

with open('encoder_final.pkl', 'rb') as file_2:
  encoder_inf = pickle.load(file_2)

with open('model_forest_opt.pkl', 'rb') as file_3:
  model_forest_inf = pickle.load(file_3)

with open('num_columns_final.txt', 'r') as file_4:
  num_columns_inf = json.load(file_4)

with open('cat_columns_final.txt', 'r') as file_5:
  cat_columns_inf = json.load(file_5)

In [3]:
# Create New Data 

data_inf = {
    'limit_balance': 250000, 
    'pay_amt_1': 120000, 
    'pay_amt_2': 100000, 
    'pay_amt_3': 110000, 
    'pay_amt_4': 80000, 
    'pay_amt_5': 90000, 
    'pay_amt_6': 100000, 
    'pay_1': 0, 
    'pay_2': 0, 
    'pay_3': 0,
    'pay_4': 1,
    'pay_5' : 2,
    'pay_6' : 1
}

data_inf = pd.DataFrame([data_inf])
data_inf

limit_balance  pay_amt_1  pay_amt_2  pay_amt_3  pay_amt_4  pay_amt_5  \
0         250000     120000     100000     110000      80000      90000   

   pay_amt_6  pay_1  pay_2  pay_3  pay_4  pay_5  pay_6  
0     100000      0      0      0      1      2      1

In [4]:
#Pemisahan kolom numerical dan categorical
data_inf_num = data_inf[num_columns_inf]
data_inf_cat = data_inf[cat_columns_inf]

data_inf_num

limit_balance  pay_amt_1  pay_amt_2  pay_amt_3  pay_amt_4  pay_amt_5  \
0         250000     120000     100000     110000      80000      90000   

   pay_amt_6  
0     100000

In [5]:
#Scaling Data Inference
data_inf_num_scaled = scaler_inf.transform(data_inf_num)
data_inf_num_scaled

array([[ 0.61111111, 29.18008422, 23.80430814, 26.53562654, 21.17751959,
        23.72411014, 25.06687046]])

In [6]:
#Encoding Data Inference
data_inf_cat_encoded =  encoder_inf.transform(data_inf_cat)
data_inf_cat_encoded

array([[2., 2., 2., 3., 4., 3.]])

In [7]:
#Concate all feature
data_inf_final = np.concatenate([data_inf_num_scaled, data_inf_cat_encoded], axis=1)
data_inf_final

array([[ 0.61111111, 29.18008422, 23.80430814, 26.53562654, 21.17751959,
        23.72411014, 25.06687046,  2.        ,  2.        ,  2.        ,
         3.        ,  4.        ,  3.        ]])

In [8]:
# Predict using Random Forest Opt
y_pred_inf = model_forest_inf.predict(data_inf_final)
y_pred_inf

array([0], dtype=int64)